"""table_def 1.0

Revision ID: 3f6751477d6c
Revises: 
Create Date: 2021-10-03 15:17:30.048001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6751477d6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
            'trs',
            sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
            sa.Column('account',sa.String,  nullable=False),
            sa.Column('currency',sa.String,  nullable=False),
            sa.Column('adate',sa.DateTime, nullable=False),
            sa.Column('amount',sa.Float, nullable=False),
            sa.Column('descr',sa.UnicodeText, nullable=False),
            sa.Column('ahash',sa.String, nullable=False)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trs')
    # ### end Alembic commands ###
