"""ahash unique

Revision ID: e437ccb2bbb5
Revises: 3f6751477d6c
Create Date: 2021-10-03 15:24:48.653903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e437ccb2bbb5'
down_revision = '3f6751477d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trs_ahash'), 'trs', ['ahash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trs_ahash'), table_name='trs')
    # ### end Alembic commands ###
