cat_defs:
  inet_mobile:
    - INTERSVYAZ
    - MegaFon
    - TELE2
    - ROSTELECOM
  comiss:
    - Комиссия
  sadik : 
    - Парфенов\s+Сергей
  kv_otop : 
    - RU GOROD74.RU
  kv : 
    - в пользу"ЧЕЛЯБИНВЕСТБАНК"
  cash : 
    - Alfa Iss
  dolina : 
    - DOLINA
  molnia : 
    - MOLNIA
  taxi : 
    - TAXI
  eats : 
      - MAGNIT
      - PYATEROCHKA
      - Магазины продуктовые
  to KATE : 
    - на \+79511286005
  gas : 
    - GAZPROMNEFT
    - AZS
    - АЗС
  shopping:
    - агазины

  to RUB : 
    - CH Debit BLR MINSK P2P_SDBO_INTERNATIONAL
  to BYN : 
    - CH Debit BLR MINSK P2P SDBO NO FEE
  to CREDIT : 
    - Внутрибанковский перевод между счетами            
  Kate eats : 
      - STOLOVAYA VILKA
      - Ресторация
